services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "${BE_PORT}:${BE_PORT}"
    environment:
      - NODE_ENV=development
      - PORT=${BE_PORT}
      - DATABASE_URL=${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}

    depends_on: 
      - db

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/DATABASE_URL

volumes:
  postgres_data:
